### ISSUE TITLE
Can't clone repo in windows due to trailing whitespaces

### ISSUE THREAD

**Issue by shankar-dh** [nikbearbrown/INFO_6205_Program_Structure_and_Algorithms#1]
Unable to clone the repository on Windows machines due to trailing whitespaces in the files present under the folder 'Payal_Khatri_002775303'.

![image](https://github.com/nikbearbrown/INFO_6205_Program_Structure_and_Algorithms/assets/114494327/fef8bb87-9cf9-464c-8df9-2a2177ba474c)

**Comment by payalkhatri039** [comment]
Hi Dhanush,

Apologies for the issue due to whitespaces. I've removed all of them now. Please check.

Thanks and Regards,
Payal Khatri

________________________________
From: Dhanush Kumar Shankar ***@***.***>
Sent: Saturday, August 19, 2023 9:13 AM
To: nikbearbrown/INFO_6205_Program_Structure_and_Algorithms ***@***.***>
Cc: Payal Mahesh Khatri ***@***.***>; Assign ***@***.***>
Subject: [nikbearbrown/INFO_6205_Program_Structure_and_Algorithms] Can't clone repo in windows due to trailing whitespaces (Issue #1)


Unable to clone the repository on Windows machines due to trailing whitespaces in the files present under the folder 'Payal_Khatri_002775303'.

[image]<https://user-images.githubusercontent.com/114494327/261763992-fef8bb87-9cf9-464c-8df9-2a2177ba474c.png>

**Comment by payalkhatri039** [comment]
Hi Professor,

I hope this email finds you well. I’m Payal Khatri, a recent graduate of the Software Engineering Systems program at Northeastern University. I had the privilege of taking the Program Structure and Algorithms course under your guidance.
I am very interested in joining Bear Brown Company as a volunteer and have heard excellent things about the work being done there. I would greatly appreciate the opportunity to contribute and learn from your team.
My EAD date starts on October 15, after which I will be eligible to work. I would be grateful if you could let me know if there are any openings or if I might be considered for any volunteer roles.
Thank you for your time and consideration. I look forward to hearing from you.
Best regards,
Payal Khatri
